const ENVIRONMENTS = {
  DEVELOPMENT: 'development',
  ANALYZER: 'analyzer',
  PRODUCTION: 'production',
} as const;

const CURRENT_ENVIRONMENT = process.env.NODE_ENV || ENVIRONMENTS.DEVELOPMENT;

const FLAGS = {
  IS_DEVELOPMENT: CURRENT_ENVIRONMENT === ENVIRONMENTS.DEVELOPMENT,
  IS_ANALYZER: CURRENT_ENVIRONMENT === ENVIRONMENTS.ANALYZER,
  IS_PRODUCTION: CURRENT_ENVIRONMENT === ENVIRONMENTS.PRODUCTION,
};

export {
  FLAGS,
};
