name: linting, testing, building
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm ci
        if: always()
      - name: build production project
        run: npm run build:production
        if: always()
      - name: unit testing
        run: npm run test:unit
        if: always()
      - name: ui-test
        run: npm run test:ui-loki:ci
        if: always()
      - name: eslint
        run: npm run eslint
        if: always()
